#!/bin/bash

cd ../

function clone_or_pull {
  if [ ! -d "$1" ]; then
    git clone git@github.com:$2.git
  else
    cd $1
    git pull
    cd ../
  fi
}


# reader-app
clone_or_pull reader-app enrichreader/reader-app
cd reader-app
npm install && npm run build
cd ../

# reader-backend
clone_or_pull reader-backend enrichreader/reader-backend
cd reader-backend
RESTART_MODE=always RAILS_ENV=production PORT=3000 docker compose up -d
cd ../

# enrichreader-lfs
clone_or_pull enrichreader-lfs Roriz/enrichreader-lfs

# active_genie_sass
clone_or_pull active_genie_sass Roriz/active_genie_sass
cd active_genie_sass
RESTART_MODE=always RAILS_ENV=production PORT=3001 docker compose up -d

# sudo systemctl stop caddy
caddy stop
caddy start